version: "3.9"

services:
    mysql:
        container_name: mysqlserver
        image: mysql
        restart: always
        ports:
            - "3306:3306"
        env_file:
            -   dev-env.env
        volumes:
            - mysqldata:/var/lib/mysql
    spring-app:
        container_name: brandondev-backend
        image: bcspace/brandondev-backend
        restart: always
        ports:
            - "25565:25565"
        env_file:
            - dev-env.env
        depends_on:
            - mysql
        extra_hosts:
            - host.docker.internal:host-gateway
volumes:
    mysqldata:
        external: true
