CREATE TABLE ANALYTICS (
    A_ID INT NOT NULL AUTO_INCREMENT,
    A_TYPE VARCHAR(100) NOT NULL,
    A_IP VARCHAR(100),
    A_SESSION VARCHAR(100),
    A_USER TEXT,
    A_CRTD_DATE DATETIME,
    PRIMARY KEY (A_ID)
);